# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userinfo_introdution',
            field=models.TextField(default=111, verbose_name='简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userinfo_speciality',
            field=models.CharField(default=111, max_length=64, verbose_name='特长'),
            preserve_default=False,
        ),
    ]
