# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190515_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='配图'),
            preserve_default=False,
        ),
    ]
