# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_article_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(upload_to='static/article_pic', verbose_name='配图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Data Structure And Algorithm'), (3, "Marx's philosophy"), (4, 'Others')], default=None),
        ),
    ]
