# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-27 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20190527_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userinfo_avatar_full',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
    ]
